#!/bin/bash

main() {
    if ! command -v chezmoi &> /dev/null; then
        brew install chezmoi
    fi

    chezmoi init --source "$HOME/dotfiles" --apply

    . scripts/brew
    . scripts/macOS
    . scripts/oh_my_zsh
    . scripts/xcode_cli_tools
    . scripts/cursor
}

main
