#!/bin/bash

main() {
	ln -s ~/dotfiles/.zshrc ~/.zshrc

	. scripts/brew
	. scripts/macOS
	. scripts/oh_my_zsh
	. scripts/stow
	. scripts/ssh
	. scripts/xcode_cli_tools
	. scripts/cursor
	. scripts/claude
}

main
