#!/bin/bash

install_homebrew() {
	if command -v brew &>/dev/null; then
		echo "Homebrew already installed."
	else
		echo "Homebrew not found - installing..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
}

setup_homebrew() {
	install_homebrew
	brew bundle
}

setup_homebrew