#!/bin/bash

CURSOR_DIR="$HOME/Library/Application Support/Cursor/User"

mkdir -p "$CURSOR_DIR"

ln -sf "$HOME/.config/cursor/settings.json" "$CURSOR_DIR/settings.json"

echo "Cursor setup complete ✅"
