#!/bin/bash

install_xcode_cli_tools() {
	if xcode-select -p &>/dev/null; then
		echo "Xcode Command Line Tools already installed."
	else
		echo "Xcode Command Line Tools not found - installing..."
		xcode-select --install
		sudo xcodebuild -license accept
	fi
}

install_xcode_cli_tools

